# Generated by Django 5.2.4 on 2025-07-31 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='secuencias/')),
                ('orden_correcto', models.PositiveIntegerField(help_text='Posición correcta de la imagen en la secuencia')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='juegos.juego')),
            ],
        ),
    ]
